#pragma once

#include "CoreMinimal.h"
#include "AssetActionUtility.h"

#include "BertaAssetNamingActions.generated.h"

/**
 * @class UBertaAssetNamingActions
 *
 * AssetActionUtility that adds prefix-based renaming operations to the
 * Content Browser right-click context menu when one or more assets are selected.
 *
 * The prefix map is owned by UBertaAssetNamingUtils — this class is responsible
 * only for applying those prefixes to the current selection.
 *
 * Supported operations:
 *   - AddPrefixes: Renames selected assets to include the standard Unreal naming
 *                  prefix for their class (e.g. SM_, T_, MI_), based on the shared
 *                  prefix map in UBertaAssetNamingUtils. Assets that already carry
 *                  the correct prefix are skipped.
 */
UCLASS()
class BERTADEVKITEDITOR_API UBertaAssetNamingActions : public UAssetActionUtility
{
	GENERATED_BODY()

public:
	/**
	 * Renames selected Content Browser assets by prepending the standard class prefix
	 * defined in UBertaAssetNamingUtils::GetPrefixMap().
	 *
	 * Assets that already carry the correct prefix are skipped silently.
	 * Assets whose class is not in the map are skipped with a warning log.
	 * UMaterialInstanceConstant assets have "M_" and "_Inst" stripped before
	 * "MI_" is applied, to handle names auto-generated by the engine.
	 */
	UFUNCTION(CallInEditor)
	void AddPrefixes();
};
